### ISSUE TITLE
'gluster-block list <volume>' dumps a core when executed as non-root

### ISSUE THREAD

**Issue by nixpanic** [gluster/gluster-block#37]
The following backtrace:

~~~
Core was generated by `gluster-block list block'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ___fprintf_chk (fp=0x0, flag=1, format=0x562a6629deda "[%s] %s: %s [at %s+%d :<%s>]\n") at fprintf_chk.c:30
30        _IO_acquire_lock_clear_flags2 (fp);
(gdb) bt
#0  ___fprintf_chk (fp=0x0, flag=1, format=0x5575324eceda "[%s] %s: %s [at %s+%d :<%s>]\n") at fprintf_chk.c:30
#1  0x00005575324eadf7 in fprintf (__fmt=0x5575324eceda "[%s] %s: %s [at %s+%d :<%s>]\n", __stream=0x0) at /usr/include/bits/stdio2.h:97
#2  glusterBlockCliRPC_1 (cobj=<optimized out>, opt=<optimized out>) at gluster-block.c:159
#3  0x00005575324e992f in glusterBlockList (json=<optimized out>, options=0x7ffe474882f8, argcount=3) at gluster-block.c:425
#4  glusterBlockParseArgs (options=0x7ffe474882f8, count=3) at gluster-block.c:527
#5  main (argc=<optimized out>, argv=0x7ffe474882f8) at gluster-block.c:580
(gdb) f 2
#2  glusterBlockCliRPC_1 (cobj=<optimized out>, opt=<optimized out>) at gluster-block.c:159
159         LOG("cli", GB_LOG_ERROR, "%s", errMsg);
(gdb) p errMsg
$1 = "/var/run/gluster-blockd.socket: connect failed (Permission denied)", '\000' <repeats 1981 times>
~~~

It seems the error message is appropriate, but is not logged. Possibly commit a2dff3381ac1d14bd42d478a6c96216750009741 fixes the coredump and gives the user the error back?

**Comment by nixpanic** [comment]
Btw, this was with gluster-block-0.2.1-2.fc26.x86_64 from the Fedora 26 (testing) repository.

**Comment by pkalever** [comment]
@lxbsz for some reason I cannot add you here, we should fix this part.

**Comment by lxbsz** [comment]
@pkalever Yeah, well received.

**Comment by pkalever** [comment]
Have tested this on latest master and it works for me. Hence close this as resolved. Thanks for reporting.
